### ISSUE TITLE
Compiling https download poco example fails under OSX

### ISSUE THREAD

**Issue by ruipires** [lasote/conan-poco#1]
Creating a simple project depending on Poco/1.6.1@lasote/stable and using the https://github.com/pocoproject/poco/blob/develop/NetSSL_OpenSSL/samples/download/src/download.cpp as the source code, it fails, under Mac OSX with the following error:

```
In file included from /Users/rui/.conan/data/Poco/1.6.1/lasote/stable/package/48ea149d546e58e2deb79b0af9ed4004e92f7298/include/Poco/Net/SSLManager.h:24:
In file included from /Users/rui/.conan/data/Poco/1.6.1/lasote/stable/package/48ea149d546e58e2deb79b0af9ed4004e92f7298/include/Poco/Net/VerificationErrorArgs.h:24:
/Users/rui/.conan/data/Poco/1.6.1/lasote/stable/package/48ea149d546e58e2deb79b0af9ed4004e92f7298/include/Poco/Net/X509Certificate.h:27:10: fatal error: 
      'wincrypt.h' file not found
#include <wincrypt.h>
```

I would love to submit a patch, but I am still trying to figure out the finer details of conan.

**Comment by lasote** [comment]
It fails in linux too. Let me check it, It could be a bug in the conan's poco's package

**Comment by lasote** [comment]
Yes, I've detected a bug, I will need to regenerate the packages so it will long some hours. 
The 1.7.2 version has the same bug, Thank you very much for try it.

**Comment by ruipires** [comment]
My pleasure. I did try rebuilding the conan-poco project, but it was failing in another place.

Running conan install .. --build on a project depending on conan-poco would eventually fail with:
```
OpenSSL/1.0.2g@lasote/stable: Downloading https://www.openssl.org/source/openssl-1.0.2g.tar.gz
OpenSSL/1.0.2g@lasote/stable: ERROR: Error while executing source(): EOF occurred in violation of protocol (_ssl.c:590)
ERROR: OpenSSL: EOF occurred in violation of protocol (_ssl.c:590)
```

This one left me clueless. I could download the file via browser or wget. Maybe its a certificate issue ?

**Comment by lasote** [comment]
Hi, I don't have a clue about the error, never seen before. maybe a connection error? Have you try to retry?

I assume that the package you need is already generated because linux builds are almost ready, but 1.6.1 is still being generated, you can check the progress here:

https://travis-ci.org/lasote/conan-poco/builds/131426931
https://ci.appveyor.com/project/lasote/conan-poco

When it finish I'll launch 1.7.2

**Comment by ruipires** [comment]
Seems to be working perfectly now.
