### ISSUE TITLE
Undefined Reference Errors with SocketAddress constructor.

### ISSUE THREAD

**Issue by john01dav** [lasote/conan-poco#10]
Hello,

I just found the Poco libraries, and they look like a really nice tool to use. To get used to its network library, I decided to make a very simple IRC-like chat system. All went well, until I encountered an issue: an undefined reference error.

The error happens on the following line of code:
`g_socket = Poco::Net::StreamSocket(Poco::Net::SocketAddress(address.c_str(), 16384));`

When I compile with that line of code, I get the following  error:
`undefined reference to 'Poco::Net::SocketAddress::SocketAddress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short)'`

I am using gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) on Ubuntu 17.04 x64 with CMake 3.8 (via CLion).

What can I do to correctly compile my program? (Note: I will not be available to respond to this issue for ~1 week after posting it, since I will not have access to a working Internet connection. I just want to get it on the project's radar before I go.)

Here is the full program so far:
```#include <string>
#include <stdexcept>
#include <iostream>
#include <Poco/Net/SocketAddress.h>
#include <Poco/Net/StreamSocket.h>
#include <Poco/Net/ServerSocket.h>
#include <Poco/Net/SocketStream.h>

Poco::Net::StreamSocket g_socket;

void setupConnection();
void receiveConnection();
void connect();
void sendReceiveMessages();

int main(){
    setupConnection();
    sendReceiveMessages();
    return 0;
}

void setupConnection(){
    std::cout << "Select an option:" << std::endl;
    std::cout << "1. Connect to another instance of NetChat." << std::endl;
    std::cout << "2. Wait for another instance of NetChat to connect to this instance." << std::endl;
    std::cout << "Your option: ";

    unsigned option;
    std::cin >> option;

    switch(option){
        case 1:
            connect();
            break;
        case 2:
            receiveConnection();
            break;
        default:
            throw std::runtime_error("Invalid option: " + std::to_string(option));
    }
}

void receiveConnection(){
    std::cout << "Waiting for incoming connection..." << std::endl;
    Poco::Net::ServerSocket serverSocket(16384);
    g_socket = serverSocket.acceptConnection();
    std::cout << "Connected!" << std::endl;
}

void connect(){
    std::string addressStr;
    std::cout << "Enter an address to connect to: ";
    std::cin >> addressStr;
    Poco::Net::SocketAddress address(addressStr, 16384);
    g_socket = Poco::Net::StreamSocket(address);
    std::cout << "Connected!" << std::endl;
}

void sendReceiveMessages(){

}
```

**Comment by lasote** [comment]
Hi! I would need the conanfile and CMakeLists.txt that you are using (if you are using CMake).
It looks like a link error, I need to see if it's an error in the conan package or in your build script.
Thanks!

**Comment by john01dav** [comment]
Here's a zip of my whole project, including CMakeLists.txt. It should be easy to fully reproduce the error from it.
[netchat.zip](https://github.com/lasote/conan-poco/files/1210360/netchat.zip)

**Comment by lasote** [comment]
Thanks, I was able to reproduce the error in a Docker container. It's funny, in OSX it's working fine. I'll report again with news.

**Comment by lasote** [comment]
I have no idea why it fails to link, the libraries are there, the linked libraries are ok... I don't understand.

**Comment by lasote** [comment]
I got it. In the conan install command specify "-s compiler=gcc -s compiler.libcxx=libstdc++11" (you can change your default profile). The problem was that it was trying to link you c++11 code against a non c++11 poco binaries.
