### ISSUE TITLE
Poco WebSockets throw "Address not supported"

### ISSUE THREAD

**Issue by arnemertz** [lasote/conan-poco#3]
Hi, 
I'm again playing around with Conan and having issues with the Poco libraries. The simple web server example of the ["Poco Guided Tour"](http://pocoproject.org/docs/00100-GuidedTour.html#5) throws a `Net Exception: Address family not supported`

I am on Xubutu 16.04, using Clang 3.8 with CLion/CMake

This is my conanfile:

```
[requires]
Poco/1.7.3@lasote/stable
Boost/1.60.0@lasote/stable

[generators]
cmake
```

I tried to reduce the problem, the minimal reproducible code is extremely simple:

```
#include "Poco/Net/ServerSocket.h"
int main() {
  Poco::Net::ServerSocket sock{8080};
}
```

Have I missed some option somewhere or is the package not compatible to my setup somehow?

My conan settings are:
```
arch=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=3.8
```

**Comment by arnemertz** [comment]
Just tested the same with g++-4.9 and it worked there.

**Comment by memsharded** [comment]
I have tried it in Win, and worked fine. I guess you are building it from sources, as there is no Clang precompiled binary. What is your CMakeLists?

**Comment by memsharded** [comment]
I have tried in Ubuntu14 with clang 3.6 and libstdc++ (I have no access now to the newer 16.04 and libstdc++11), and everything worked fine too. Will try to install an upgraded VM to try it.

**Comment by memsharded** [comment]
It worked also in Ubuntu 16, with these settings (clang 3.8 and libstdc++11), and building from source. Added ``-std=c++14`` in my CMakeLists.txt. It is true that I removed the Boost requirement, it is not needed for this test, have you tried to remove it? It would be a weird interaction, but just in case.

**Comment by arnemertz** [comment]
Hi, thanks for looking into this!
My CMakeLists.txt is the following:
´´´
cmake_minimum_required(VERSION 2.8.12)

set( PROJ_NAME fix )
file( GLOB_RECURSE PROJ_SOURCES src/*.cpp )

project( ${PROJ_NAME} )

include(build/conanbuildinfo.cmake)
conan_basic_setup()

add_executable( ${PROJ_NAME} ${PROJ_SOURCES} )
target_link_libraries(${PROJ_NAME} ${CONAN_LIBS})

set_property(TARGET ${PROJ_NAME} PROPERTY CXX_STANDARD 14)
´´´

I built without boost, but with the same result. I learned that Poco is sensible when it comes to the std flag. Have I built Poco without the `-std=c++14`? How can I tell and make sure that I build it right?

**Comment by memsharded** [comment]
It runs well with that CMakeLists too. I don't know what can be happening. I ran:

```bash
$ mkdir build && cd build
$ conan install .. -s compiler=clang -s compiler.version=3.8 -s compiler.libcxx=libstdc++11
$ cmake .. -DCMAKE_BUILD_TYPE=Release
$ cmake --build .
$ ./bin/fix
```

I only had to fix the sources path in CMakeLists. I am running Ubuntu, not Xubuntu, 16.04, but I think it should be the same regarding this.

**Comment by arnemertz** [comment]
The only difference I see now to my stuff is the Release build - I build the project in Debug and Poco in Release - I'll try if the problem might reside there.

**Comment by memsharded** [comment]
Yes, please, try with both with the same config. Having dependencies in other build_type than the project is sometimes a problem, it is typical to produce runtime errors at least in Win.

**Comment by arnemertz** [comment]
OK, that seems to be it: if I use the Release flag, it runs just fine. Using Debug flag, I get the error again. 

Seems I have to switch between two Poco builds depending on the Debug/Release build?

**Comment by memsharded** [comment]
Ok, great! Yes, that is correct. Every binary package contains just a binary configuration. So debug and release libraries are in different binary packages. Not only for Poco, but for other libraries too. Just run ``conan install ... -s build_type=XXXX`` before running ``cmake -DCMAKE_BUILD_TYPE=XXXX`` and everything will work

**Comment by arnemertz** [comment]
OK, I think I can manage to put that into the CLion build. Thanks for bearing with me :-)

**Comment by arnemertz** [comment]
well... seems to work in Release, but when I build both Poco and the app in Debug I still get the error. Is there a way to pass the -DCMAKE_CXX_STANDARD=14 flag to the Poco Debug build in Conan?

**Comment by memsharded** [comment]
Confirmed. It seems some weird behavior of clang in Debug, as I have tested in gcc 5.4 (Debug) without problems.

@lasote It can be solved adding to the package ``CMakeLists.txt``:

```cmake
PROJECT(conanpoco)
cmake_minimum_required(VERSION 2.8)
include(${CMAKE_CURRENT_SOURCE_DIR}/../conanbuildinfo.cmake)
CONAN_BASIC_SETUP()
set(CMAKE_CXX_STANDARD 14)
include("CMakeListsOriginal.cmake")
```

The CMAKE_CXX_STANDARD has fallback behavior, so it should work with non c++14 compilers. However I am concerned that this somehow would change the packages, or what would happen to MSVC, probably running through CI will tell.

@arnemertz The issue is that you cannot pass arbitrary cmake flags to upstream dependencies. Please note, that upstream dependencies might not use CMake at all (as Boost, Openssl, etc), so it would'nt make sense. Packages are controlled via their ``options`` interface. Let`s see if this flag added to the Poco package recipe fixes it. Thanks for reporting!

**Comment by arnemertz** [comment]
@memsharded makes sense, thanks.
For now that means that either I'll have to build the lib that wraps Poco in Release, or use an alternative.

**Comment by lasote** [comment]
@arnemertz Our CI is testing the packages with the new flag. In a couple hours will know if anything is broken. If everything is ok I will upload the recipe to stable channel.

**Comment by arnemertz** [comment]
@lasote wow that is quick :+1:

**Comment by lasote** [comment]
It seems it's a little more complicated. If you activate the "CMAKE_CXX_STANDARD 14" the binaries are incompatible if the user's project doesn't activate the flag too (just with clang debug, not problem at all with gcc, that's a very strange behavior).  We are going to add an option to the recipe to activate the 14 standard, default to false, and automatic set to true on clang + debug. Will report again soon.

**Comment by arnemertz** [comment]
Eek. Sorry if I'm causing inconveniences.

**Comment by lasote** [comment]
Don't worry, We need your feedback ;)
Please try this:

```
conan install -u -o Poco:cxx_14=True
```

The "-u" if to update the recipe, and the cxx_14 is for enable the CMAKE_CXX_STANDARD 14.

**Comment by arnemertz** [comment]
Will do. Shouldn't Clang + Debug trigger that option anyways? I saw the commit and am trying to understand the recipe. 
I'll try both explicit and implicit `cxx_14` I think :-)

**Comment by arnemertz** [comment]
`conan install .. -u -o Poco:cxx_14=True -s build_type=Debug --build Poco`  
-> compiles and runs without the error!

**Comment by arnemertz** [comment]
`conan install .. -u -s build_type=Debug --build Poco`

-> implicit cxx_14 fails:

    -- CMake 3.5.1 successfully configured Poco using Unix Makefiles generator
    -- Installation target path: /usr/local
    -- C_FLAGS:  =  
    -- CMAKE_C_FLAGS_DEBUG:=-g   -D_DEBUG
    -- CMAKE_C_FLAGS_RELEASE:=-O3 -DNDEBUG
    -- CMAKE_C_FLAGS_MINSIZEREL:=-Os -DNDEBUG
    -- CMAKE_C_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
    -- 
    -- 
    -- CXX_FLAGS:=   -stdlib=libstdc++
    -- CMAKE_CXX_FLAGS_DEBUG:=-g -D_DEBUG
    -- CMAKE_CXX_FLAGS_RELEASE:=-O3 -DNDEBUG
    -- CMAKE_CXX_FLAGS_MINSIZEREL:=-Os -DNDEBUG
    -- CMAKE_CXX_FLAGS_RELWITHDEBINFO:=-O2 -g -DNDEBUG
    -- Building: XML
    -- Building: JSON
    -- Building: MongoDB
    -- Building: Util
    -- Building: Net
    -- Building: NetSSL_OpenSSL
    -- Building: Crypto
    -- Building: Data
    -- Building: Zip
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        CXX_14

**Comment by lasote** [comment]
We decided to not set the option automatically with the combination clang+debug because if the user that is depending on Poco don't have the cxx 14 flag in his project, it will fail.

I've solved the CMake warning. Thanks for notice it!

**Comment by arnemertz** [comment]
Alright, thanks for fixing it so fast! 
Seems like I have no more excuses to procrastinate  that  first project in the "4C" environment ;-)
