### ISSUE TITLE
Cannot compile with msys2 on windows

### ISSUE THREAD

**Issue by henryborchers** [lasote/conan-poco#9]
on line 112 of your conan,py 

```
if self.settings.os == "Windows":
   if self.settings.compiler.runtime == "MT" or self.settings.compiler.runtime == "MTd":
      options_poco += " -DPOCO_MT=ON"
  else:
      options_poco += " -DPOCO_MT=OFF"
 
```
This make it impossible to compile with GCC on windows because there isn't a compiler.runtime setting.

**Comment by lasote** [comment]
Thanks for the tip. I'm fixing it.

**Comment by lasote** [comment]
It's pushed, will take some time to update the packages in CI. Thanks!
